// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rezbeuxknwdykpphomcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlemJldXhrbndkeWtwcGhvbWNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3MDQwNDcsImV4cCI6MjA4NTI4MDA0N30.4rXmVBYrs2VN3vehSIe1qI_TKupi9Z-S5Sd8wiNUJUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});